# https://zenn.dev/jnst/scraps/5313ae383369d0

# https://stackoverflow.com/a/56039373
# https://leighmcculloch.com/posts/tool-go-check-no-globals-no-inits/


# linters:
#   # Disable all linters.
#   # Default: false
#   disable-all: true
#   # Enable specific linter
#   # https://golangci-lint.run/usage/linters/#enabled-by-default
#   enable:
#     - asasalint
#     - asciicheck
#     - bidichk
#     - bodyclose
#     - containedctx
#     - contextcheck
#     - cyclop
#     - deadcode
#     - decorder
#     - depguard
#     - dogsled
#     - dupl
#     - dupword
#     - durationcheck
#     - errcheck
#     - errchkjson
#     - errname
#     - errorlint
#     - execinquery
#     - exhaustive
#     - exhaustivestruct
#     - exhaustruct
#     - exportloopref
#     - forbidigo
#     - forcetypeassert
#     - funlen
#     - gci
#     - ginkgolinter
#     - gocheckcompilerdirectives
#     - gochecknoglobals
#     - gochecknoinits
#     - gocognit
#     - goconst
#     - gocritic
#     - gocyclo
#     - godot
#     - godox
#     - goerr113
#     - gofmt
#     - gofumpt
#     - goheader
#     - goimports
#     - golint
#     - gomnd
#     - gomoddirectives
#     - gomodguard
#     - goprintffuncname
#     - gosec
#     - gosimple
#     - gosmopolitan
#     - govet
#     - grouper
#     - ifshort
#     - importas
#     - ineffassign
#     - interfacebloat
#     - interfacer
#     - ireturn
#     - lll
#     - loggercheck
#     - maintidx
#     - makezero
#     - maligned
#     - mirror
#     - misspell
#     - musttag
#     - nakedret
#     - nestif
#     - nilerr
#     - nilnil
#     - nlreturn
#     - noctx
#     - nolintlint
#     - nonamedreturns
#     - nosnakecase
#     - nosprintfhostport
#     - paralleltest
#     - prealloc
#     - predeclared
#     - promlinter
#     - reassign
#     - revive
#     - rowserrcheck
#     - scopelint
#     - sqlclosecheck
#     - staticcheck
#     - structcheck
#     - stylecheck
#     - tagalign
#     - tagliatelle
#     - tenv
#     - testableexamples
#     - testpackage
#     - thelper
#     - tparallel
#     - typecheck
#     - unconvert
#     - unparam
#     - unused
#     - usestdlibvars
#     - varcheck
#     - varnamelen
#     - wastedassign
#     - whitespace
#     - wrapcheck
#     - wsl
#     - zerologlint
    
# linters-settings:
#   golint:
#     min-confidence: 0
#   misspell:
#     locale: US

# bugs|comment|complexity|error|format|import|metalinter|module|performance|sql|style|test|unused
linters:
  enable:
    - errorlint
    - gocritic
    - goconst
    - gocyclo
    # - forbidigo
    # - gochecknoinits
    # - gofumpt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  gocyclo:
    min-complexity: 12
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment